### ISSUE TITLE
Change IP Router

### ISSUE THREAD

**Issue by monkey3d** [voryx/ThruwayBundle#11]
Hi,
I would change in config.yml the default ip (127.0.0.1) that the router should start on.
But in this case, when i start with the command by default : nohup php ... the router don't start with the log message : could not connect : connection refused.
My OS Server is Fedora 21 and firewalld is disabled for testing.

Any idea ?

Thanks

**Comment by davidwdan** [comment]
You'll need to tell the workers to connect to the router on the new address.  The default is `127.0.0.1`.

```YML
voryx_thruway:
    uri: "ws://12.1.0.2:9090"
    ...

```
