### ISSUE TITLE
How to use Register with location setting?

### ISSUE THREAD

**Issue by cipherchien** [voryx/ThruwayBundle#15]
Hi, 

I try to use a register controller, but I got some problems.
Here is my config setting and code:

```
voryx_thruway:
...
    locations:
#        bundles: ["OZLineBundle"]
        files:
            - "OZ\\LineBundle\\Controller\\RegisterController"
```
and the controller:
```
namespace OZ\LineBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Voryx\ThruwayBundle\Annotation\Register;

class RegisterController extends Controller
{
    /**
     * @Register("user.line.open")
     */
    public function userLineOpenAction($threadID)
    {
        try {
            $user = $this->container->getUser();  //this will make the action doesn't work.
            return $user->getUsername();   // it will make client get nothing
//            return $threadID;
        } catch (\Exception $exc) {
            return $exc->getMessage();
        }   //eof try          
    }     
```
the client side code:
```
Connection.session.call('user.line.open', [ Defaults.threadID ]).then(function(arg){
    console.log(arg);
});    
```

If the action is like this, the register can work and the client can response the response data.
```
    /**
     * @Register("user.line.open")
     */
    public function userLineOpenAction($threadID)
    {
           return $threadID;        
    }     
```

What's error with my code?
And how to get container service in Register action?

Thank you.
