### ISSUE TITLE
How call/publish from another service/controller

### ISSUE THREAD

**Issue by patie** [voryx/ThruwayBundle#28]
Hi,

i have registered some wamp methods in php, when i call it from javascript works great, this also work in the same controller where are methods registered

but

when i need call it from another service/controller (i need publish, or call call with publish in), i give error like this - wamp.error.not_authorized

2015-10-29T13:11:42.1927460 notice [Thruway\Peer\Client 22073] Changing PHP precision from 14 to 16 2015-10-29T13:11:42.1948920 info [Thruway\Peer\Client 22073] New client created 2015-10-29T13:11:42.1958070 info [Thruway\Transport\PawlTransportProvider 22073] Starting Transport 2015-10-29T13:11:42.2112130 info [Thruway\Transport\PawlTransportProvider 22073] Pawl has connected 2015-10-29T13:11:42.2177340 debug [Thruway\Transport\PawlTransportProvider 22073] Received: [3,{},"wamp.error.not_authorized"] 2015-10-29T13:11:42.2179390 debug [Thruway\Peer\Client 22073] Client onMessage: [Thruway\Message\AbortMessage] 2015-10-29T13:11:42.2182040 warning [Thruway\Transport\PawlTransportProvider 22073] Exception occurred during onMessage: Got the following error when trying to call 'myCallMethod': wamp.error.not_authorized 2015-10-29T13:11:42.2183570 info [Thruway\Transport\PawlTransportProvider 22073] Pawl has closed

any idea where is problem please? its needed authenthicate php client, if yes, how? or another way to do publish in other service/controller? 

thanks

**Comment by mbonneau** [comment]
Hi @patie ,

I am not exactly sure what your configuration is, but I suspect that you are connecting to the port that requires authentication.

When you configure Thruway with the bundle, it will create 2 ports, one is a trusted port. You should use the trusted port with these services which will have authorization to do anything.

```yml
#app/config/config.yml

voryx_thruway:
    realm: 'realm1'
    url: 'ws://127.0.0.1:8081' #The url that the clients will use to connect to the router
    router:
        ip: '127.0.0.1'  # the ip that the router should start on
        port: '8080'  # public facing port.  If authentication is enabled, this port will be protected
        trusted_port: '8081' # Bypasses all authentication.  Use this for trusted clients.
```

The clients (your php services) will connect to voryx_thruway.url.  Notice in this example that it is the same as the trusted port.

**Comment by patie** [comment]
my conf looks like this, 0.0.0.0 can be, also 127.0.0.1, the same result

```yaml
voryx_thruway:
    realm: 'realm1'
    url: 'ws://0.0.0.0:8081' 
    router:
        ip: '0.0.0.0'
        port: '8080'  
        trusted_port: '8081' 
        authentication: true 
    user_provider: 'component.account.repository.user'
    locations:
        files:
            - "App\\AppBundle\\Controller\\ResourceController"
```

how can i initiate client for trusted port?

$this->get('thruway.client')->call('someRegisteredMethod',[]); dont work, because wamp.error.not_authorized

**Comment by patie** [comment]
when i added trusted_url looks like its working now, like this

```yaml
voryx_thruway:
    realm: 'realm1'
    url: 'ws://0.0.0.0:8081'
    trusted_url: 'ws://0.0.0.0:8081'
    router:
        ip: '0.0.0.0' 
        port: '8080'  
        trusted_port: '8081'
        authentication: true 
    user_provider: 'component.account.repository.user'
    locations:
        files:
            - "App\\AppBundle\\Controller\\ResourceController"
```

but when i have $this->get('thruway.client')->call('someRegisteredMethod',[]); in controller, return echo to respone (i see it in generated page on begin), its normal ? :)
