### ISSUE TITLE
How to prevent RPC registered on server from disappearing

### ISSUE THREAD

**Issue by Jitra** [voryx/ThruwayBundle#31]
I registered RPC on server with annotation
```php
/**
*@Register("games.snake.newplayer",serializerEnableMaxDepthChecks=true, worker="add-snake")
*/
```
 and I can call it but when I leave let's say for 5-10 minutes it is no longer available and I must restart server to make it available again. 

To run server I am using command: 
```php
nohup php app/console thruway:process start & 
```

**Comment by davidwdan** [comment]
@Jitra can you share the `voryx_thruway` portion of your config?

**Comment by Jitra** [comment]
```yaml
voryx_thruway:
    realm: 'realm1'
    url: 'ws://192.168.2.111:8081/games' #The url that the clients will use to connect to the router
    trusted_url: 'ws://0.0.0.0:8081'
    router:
        ip: '0.0.0.0'  # the ip that the router should start on
        port: '8080'  # public facing port.  If authentication is enabled, this port will be protected
        trusted_port: '8081' # Bypasses all authentication.  Use this for trusted clients.
        authentication: true # true will load the AuthenticationManager
        authorization: my_authorization_manager
    user_provider: 'fos_user.user_manager' 
    locations:
#        bundles: [GamesSnakeBundle]
        files:
            - "Games\\SnakeBundle\\RPC\\MoveRpc"
            - "Games\\SnakeBundle\\RPC\\AddPlayerRpc"
            - "Games\\SnakeBundle\\RPC\\PingPong"
            - "Games\\SnakeBundle\\RPC\\StartGameRpc"
```
With this configuration I don't have that issue on my localhost the only change on my production is  url: 'ws://production.net:8081/games'. Probably it's my production server's fault somehow. I succeeded to avaid this issue by sending some test data to my rpcs every minute.
