### ISSUE TITLE
PHP client not connecting to server, not sure how to debug

### ISSUE THREAD

**Issue by mikeysteele** [voryx/ThruwayBundle#39]
Hi,

I have a problem where publishing from the PHP client doesn't work. There's no obvious errors, the client just doesn't appear to connect to the router.  Clients connected using Autobahn.js work fine

Here is my config

```yaml
voryx_thruway:
    realm: 'realm1'
    url: 'ws://127.0.0.1:8881' #The url that the clients will use to connect to the router
    router:
        ip: '127.0.0.1'  # the ip that the router should start on
        port: '8880'  # public facing port.  If authentication is enabled, this port will be protected
        trusted_port: '8881' # Bypasses all authentication.  Use this for trusted clients.
        authentication: true
```
And here is the line in my controller which is supposed to send the message:
```php
$this->get('thruway.client')->publish('test.event', ['hello there']);
```

I'm guessing the connection fails for some reason between the PHP client and the server, but I can't find any errors anywhere. Is there something I've missed?
