### ISSUE TITLE
How to react to on client connect

### ISSUE THREAD

**Issue by frankadrian** [voryx/ThruwayBundle#72]
Hi,

Thanks so much for this easy to use bundle! 
I have a very simple setup and would like to know if its possible to react to a client connecting to the default realm?
This is my config:

```
voryx_thruway:
    realm: 'realm1'
    url: 'ws://127.0.0.1:8000' #The url that the clients will use to connect to the router
    router:
        ip: '127.0.0.1'  # the ip that the router should start on
        port: '8000'  # public facing port.  If authentication is enabled, this port will be protected
        authentication: false # true will load the AuthenticationManager
    locations:
        bundles: ["AppBundle"]

```

I would greatly appreciate any pointers 🙏
