### ISSUE TITLE
In memory user provider doesn't work.

### ISSUE THREAD

**Issue by ThePixelDeveloper** [voryx/ThruwayBundle#84]
Trying to configure the in memory user provider and have trouble getting it working / configured. 

_thruway.yml_
``` yaml
voryx_thruway:
    realm: 'default'

    # URL that the clients will use to connect to the router
    url: 'ws://%web_socket_ip%:%web_socket_port_trusted%'

    # For the controller authentication.
    user_provider: 'in_memory_user_provider'

    router:
        # IP that the router should start on.
        ip: '%web_socket_ip%'

        # Customised authorisation checks.
        authorization: 'AppBundle\Authorization\AuthorizationManager'
        authentication: true

        # Public facing port. If authentication is enabled, this port will be protected.
        port: '%web_socket_port%'

        # Bypasses all authentication. Use this for trusted clients.
        trusted_port: '%web_socket_port_trusted%'

services:
    wamp_cra_auth:
        class: Thruway\Authentication\WampCraAuthProvider
        parent: voryx.thruway.wamp.cra.auth.client
        tags:
            - { name: thruway.internal_client }
```

_security.yml_

``` yaml
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    controller:
                        password: '%controller_secret%'
                        roles: 'ROLE_USER'

    firewalls:
        thruway:
            security: false
```

The problems arise from the Bundle extension. It's never able to find the service definition.

<img width="758" alt="screen shot 2018-04-24 at 15 00 37" src="https://user-images.githubusercontent.com/47728/39192124-6656071c-47d0-11e8-81bc-b5383a94dc8d.png">

Any help appreciated, can't load the correct user provider for it.
