### ISSUE TITLE
Publisher is not trusted

### ISSUE THREAD

**Issue by dark-matter-matters** [voryx/ThruwayBundle#99]
Hello,
My issue seems very similar to this one : https://github.com/voryx/ThruwayBundle/issues/92.

I have the very same listener class as in this tutorial : http://voryx.net/getting-started-with-the-thruwaybundle-for-symfony/

services.yaml
```
my.listener:
         class: App\EventListener\MyListener
         arguments:
             - "@thruway.client"
         tags:
             - { name: doctrine.event_listener, event: postPersist }
             - { name: doctrine.event_listener, event: postUpdate }
```
thruway.yaml 
```
voryx_thruway:
  realm: 'realm1'
  url: 'ws://127.0.0.1:8081' #The url that the clients will use to connect to the router
  enable_logging: true
  router:
    ip: '127.0.0.1'  # the ip that the router should start on
    trusted_port: '8081' # Bypasses all authentication.  Use this for trusted clients.
    port: '8080'  # public facing port.  If authentication is enabled, this port will be protected
    authentication: true # true will load the AuthenticationManager
    authorization: thruway_auth_manager
```

When using my auth provider, the clientManager is not allowed to publish anymore. When there's no authentication, it works well.

I tried making this class a Client that I add as an internal client in the router command : 

ThruwayRouterCommand.php
```
[...]
$participantListenener = $this->getContainer()->get('my.listener');
$server->addInternalClient($participantListenener);
```

How can I tell Thruway this class is trusted and does not need to be authenticated? Must be a tiny config line I'm missing.
Been trying different things for days, debugging even Thruway files, I could find that **if ($session->getTransport()->isTrusted())** of **processMessage()**  is false on _AuthenticationManager.php_ file. 

Thanks.
